[project]
name = "flpa"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Het Parekh", email = "hetparekh16@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
flpa = "flpa:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
